# Generated by Django 5.1 on 2024-08-13 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_directmessage_sender_alter_message_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='api.profile'),
        ),
    ]
